// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: watering_system

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main( lv_event_t * e);
lv_obj_t *ui_Main;
lv_obj_t *ui_Main_mainContainer;
lv_obj_t *ui_Main_infoPanel;
lv_obj_t *ui_Main_dateTimeConnContainer;
lv_obj_t *ui_Main_datetime;
lv_obj_t *ui_Main_connImg;
lv_obj_t *ui_Main_infoContainer;
lv_obj_t *ui_Main_tempImg;
lv_obj_t *ui_Main_tempLabel;
lv_obj_t *ui_Main_humidityImg;
lv_obj_t *ui_Main_humidityLabel;
lv_obj_t *ui_Main_contentContainer;
lv_obj_t *ui_Main_Pump1Container;
lv_obj_t *ui_Main_Pump2Container;
lv_obj_t *ui_Main_Pump3Container;
lv_obj_t *ui_Main_btnContainer;
void ui_event_Main_mainBtn1( lv_event_t * e);
lv_obj_t *ui_Main_mainBtn1;
lv_obj_t *ui_Main_mainBtn1Label;
void ui_event_Main_mainBtn2( lv_event_t * e);
lv_obj_t *ui_Main_mainBtn2;
lv_obj_t *ui_Main_mainBtn2Label;
void ui_event_Main_mainBtn3( lv_event_t * e);
lv_obj_t *ui_Main_mainBtn3;
lv_obj_t *ui_Main_mainBtn3Label;
// CUSTOM VARIABLES


// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings( lv_event_t * e);
lv_obj_t *ui_Settings;
lv_obj_t *ui_Settings_options;
lv_obj_t *ui_Settings_btns;
void ui_event_Settings_btn1( lv_event_t * e);
lv_obj_t *ui_Settings_btn1;
lv_obj_t *ui_Settings_btn1Label;
void ui_event_Settings_btn2( lv_event_t * e);
lv_obj_t *ui_Settings_btn2;
lv_obj_t *ui_Settings_btn2Label;
void ui_event_Settings_btn3( lv_event_t * e);
lv_obj_t *ui_Settings_btn3;
lv_obj_t *ui_Settings_btn3Label;
// CUSTOM VARIABLES


// SCREEN: ui_PumpConfig
void ui_PumpConfig_screen_init(void);
void ui_event_PumpConfig( lv_event_t * e);
lv_obj_t *ui_PumpConfig;
lv_obj_t *ui_PumpConfig_titlePanel;
lv_obj_t *ui_PumpConfig_titleLabel;
lv_obj_t *ui_PumpConfig_content;
lv_obj_t *ui_PumpConfig_enabledPanel;
lv_obj_t *ui_PumpConfig_enabledLabel;
lv_obj_t *ui_PumpConfig_enabledSwitch;
lv_obj_t *ui_PumpConfig_frequencyPanel;
lv_obj_t *ui_PumpConfig_frequencyLabel;
lv_obj_t *ui_PumpConfig_frequencyValue;
lv_obj_t *ui_PumpConfig_runtimePanel;
lv_obj_t *ui_PumpConfig_runtimeLabel;
lv_obj_t *ui_PumpConfig_runtimeValue;
lv_obj_t *ui_PumpConfig_minLightThresholdPanel;
lv_obj_t *ui_PumpConfig_minLightThresholdLabel;
lv_obj_t *ui_PumpConfig_minLightThresholdValue;
lv_obj_t *ui_PumpConfig_maxSoilThresholdPanel;
lv_obj_t *ui_PumpConfig_maxSoilThresholdLabel;
lv_obj_t *ui_PumpConfig_maxSoilThresholdValue;
lv_obj_t *ui_PumpConfig_minTempThresholdPanel;
lv_obj_t *ui_PumpConfig_minTempThresholdLabel;
lv_obj_t *ui_PumpConfig_minTempThresholdValue;
lv_obj_t *ui_PumpConfig_maxHumidityThresholdPanel;
lv_obj_t *ui_PumpConfig_maxHumidityThresholdLabel;
lv_obj_t *ui_PumpConfig_maxHumidityThresholdValue;
lv_obj_t *ui_PumpConfig_soilSensorDryPanel;
lv_obj_t *ui_PumpConfig_soilSensorDryLabel;
lv_obj_t *ui_PumpConfig_soilSensorDryValue;
lv_obj_t *ui_PumpConfig_soilSensorWetPanel;
lv_obj_t *ui_PumpConfig_soilSensorWetLabel;
lv_obj_t *ui_PumpConfig_soilSensorWetValue;
lv_obj_t *ui_PumpConfig_btn;
void ui_event_PumpConfig_btn1( lv_event_t * e);
lv_obj_t *ui_PumpConfig_btn1;
lv_obj_t *ui_PumpConfig_btn1Label;
void ui_event_PumpConfig_btn2( lv_event_t * e);
lv_obj_t *ui_PumpConfig_btn2;
lv_obj_t *ui_PumpConfig_btn2Label;
void ui_event_PumpConfig_btn3( lv_event_t * e);
lv_obj_t *ui_PumpConfig_btn3;
lv_obj_t *ui_PumpConfig_btn3Label;
// CUSTOM VARIABLES


// SCREEN: ui_WiFiSettings
void ui_WiFiSettings_screen_init(void);
void ui_event_WiFiSettings( lv_event_t * e);
lv_obj_t *ui_WiFiSettings;
lv_obj_t *ui_WiFiSettings_infoContainer;
lv_obj_t *ui_WiFiSettings_ssidLabel;
lv_obj_t *ui_WiFiSettings_ipLabel;
lv_obj_t *ui_WiFiSettings_content;
lv_obj_t *ui_WiFiSettings_btnContainer;
void ui_event_WiFiSettings_btn1( lv_event_t * e);
lv_obj_t *ui_WiFiSettings_btn1;
lv_obj_t *ui_WiFiSettings_btn1Label;
void ui_event_WiFiSettings_btn2( lv_event_t * e);
lv_obj_t *ui_WiFiSettings_btn2;
lv_obj_t *ui_WiFiSettings_btn2Label;
void ui_event_WiFiSettings_btn3( lv_event_t * e);
lv_obj_t *ui_WiFiSettings_btn3;
lv_obj_t *ui_WiFiSettings_btn3Label;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Main( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      onMainScreenLoaded( e );
}
if ( event_code == LV_EVENT_SCREEN_UNLOADED) {
      onMainScreenUnloaded( e );
}
}

void ui_event_Main_mainBtn1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Settings_screen_init);
}
}

void ui_event_Main_mainBtn2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onRunButtonClicked( e );
}
}

void ui_event_Main_mainBtn3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onPumpButtonClicked( e );
}
}

void ui_event_Settings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      onSettingsScreenLoaded( e );
}
}

void ui_event_Settings_btn1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onSettingsUpButtonClicked( e );
}
}

void ui_event_Settings_btn2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onSettingsDownClicked( e );
}
}

void ui_event_Settings_btn3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onSettingsEnterClicked( e );
}
}

void ui_event_PumpConfig( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      onPumpScreenLoaded( e );
}
}

void ui_event_PumpConfig_btn1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onPumpConfigBtn1Clicked( e );
}
if ( event_code == LV_EVENT_LONG_PRESSED) {
      onPumpConfigBtn1LongPressed( e );
}
}

void ui_event_PumpConfig_btn2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onPumpConfigBtn2Clicked( e );
}
if ( event_code == LV_EVENT_LONG_PRESSED) {
      onPumpConfigBtn2LongPressed( e );
}
}

void ui_event_PumpConfig_btn3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onPumpConfigBtn3Clicked( e );
}
}

void ui_event_WiFiSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      onWifiSettingsLoaded( e );
}
if ( event_code == LV_EVENT_SCREEN_UNLOADED) {
      onWifiSettingsUnloaded( e );
}
}

void ui_event_WiFiSettings_btn1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onWifiScreenBtn1Clicked( e );
}
}

void ui_event_WiFiSettings_btn2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onWifiScreenBtn2Clicked( e );
}
}

void ui_event_WiFiSettings_btn3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onWifiScreenBtn3Clicked( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Main_screen_init();
ui_Settings_screen_init();
ui_PumpConfig_screen_init();
ui_WiFiSettings_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Main);
}
