// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: watering_system

#ifndef _UI_COMP_PUMPCONTAINER_H
#define _UI_COMP_PUMPCONTAINER_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PumpContainer
#define UI_COMP_PUMPCONTAINER_PUMPCONTAINER 0
#define UI_COMP_PUMPCONTAINER_LABELCONTAINER 1
#define UI_COMP_PUMPCONTAINER_LABELCONTAINER_RUNNING 2
#define UI_COMP_PUMPCONTAINER_LABELCONTAINER_LABEL 3
#define UI_COMP_PUMPCONTAINER_SOIL 4
#define UI_COMP_PUMPCONTAINER_LIGHT 5
#define UI_COMP_PUMPCONTAINER_PROGRESS 6
#define _UI_COMP_PUMPCONTAINER_NUM 7
lv_obj_t *ui_PumpContainer_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
