// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: watering_system

#include "ui.h"

void ui_PumpConfig_screen_init(void)
{
ui_PumpConfig = lv_obj_create(NULL);
lv_obj_remove_flag( ui_PumpConfig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_PumpConfig,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PumpConfig, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_PumpConfig_titlePanel = lv_obj_create(ui_PumpConfig);
lv_obj_set_width( ui_PumpConfig_titlePanel, lv_pct(90));
lv_obj_set_height( ui_PumpConfig_titlePanel, lv_pct(15));
lv_obj_set_x( ui_PumpConfig_titlePanel, 1 );
lv_obj_set_y( ui_PumpConfig_titlePanel, 0 );
lv_obj_set_align( ui_PumpConfig_titlePanel, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PumpConfig_titlePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PumpConfig_titleLabel = lv_label_create(ui_PumpConfig_titlePanel);
lv_obj_set_width( ui_PumpConfig_titleLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_titleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_titleLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_titleLabel,"Pump 1");

ui_PumpConfig_content = lv_obj_create(ui_PumpConfig);
lv_obj_remove_style_all(ui_PumpConfig_content);
lv_obj_set_width( ui_PumpConfig_content, lv_pct(90));
lv_obj_set_height( ui_PumpConfig_content, lv_pct(60));
lv_obj_set_x( ui_PumpConfig_content, -1 );
lv_obj_set_y( ui_PumpConfig_content, 0 );
lv_obj_set_align( ui_PumpConfig_content, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_content,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PumpConfig_content, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_PumpConfig_content, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_PumpConfig_content, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_scroll_dir(ui_PumpConfig_content, LV_DIR_VER);

ui_PumpConfig_enabledPanel = lv_obj_create(ui_PumpConfig_content);
lv_obj_set_height( ui_PumpConfig_enabledPanel, 40);
lv_obj_set_width( ui_PumpConfig_enabledPanel, lv_pct(100));
lv_obj_set_x( ui_PumpConfig_enabledPanel, -1 );
lv_obj_set_y( ui_PumpConfig_enabledPanel, 0 );
lv_obj_set_align( ui_PumpConfig_enabledPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_enabledPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PumpConfig_enabledPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_PumpConfig_enabledPanel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_enabledPanel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_PumpConfig_enabledPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PumpConfig_enabledPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PumpConfig_enabledPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PumpConfig_enabledPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PumpConfig_enabledPanel, lv_color_hex(0x6B8AF8), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_PumpConfig_enabledPanel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_PumpConfig_enabledLabel = lv_label_create(ui_PumpConfig_enabledPanel);
lv_obj_set_width( ui_PumpConfig_enabledLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_enabledLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_enabledLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_enabledLabel,"Enabled");

ui_PumpConfig_enabledSwitch = lv_switch_create(ui_PumpConfig_enabledPanel);
lv_obj_set_width( ui_PumpConfig_enabledSwitch, 50);
lv_obj_set_height( ui_PumpConfig_enabledSwitch, 25);
lv_obj_set_align( ui_PumpConfig_enabledSwitch, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PumpConfig_enabledSwitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags


ui_PumpConfig_frequencyPanel = lv_obj_create(ui_PumpConfig_content);
lv_obj_set_height( ui_PumpConfig_frequencyPanel, 40);
lv_obj_set_width( ui_PumpConfig_frequencyPanel, lv_pct(100));
lv_obj_set_align( ui_PumpConfig_frequencyPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_frequencyPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PumpConfig_frequencyPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_PumpConfig_frequencyPanel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_frequencyPanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_PumpConfig_frequencyPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PumpConfig_frequencyPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PumpConfig_frequencyPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PumpConfig_frequencyPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PumpConfig_frequencyPanel, lv_color_hex(0x6B8AF8), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_PumpConfig_frequencyPanel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_PumpConfig_frequencyLabel = lv_label_create(ui_PumpConfig_frequencyPanel);
lv_obj_set_width( ui_PumpConfig_frequencyLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_frequencyLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_frequencyLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_frequencyLabel,"Frequency");

ui_PumpConfig_frequencyValue = lv_label_create(ui_PumpConfig_frequencyPanel);
lv_obj_set_width( ui_PumpConfig_frequencyValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_frequencyValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_frequencyValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_frequencyValue,"00:00");

ui_PumpConfig_runtimePanel = lv_obj_create(ui_PumpConfig_content);
lv_obj_set_height( ui_PumpConfig_runtimePanel, 40);
lv_obj_set_width( ui_PumpConfig_runtimePanel, lv_pct(100));
lv_obj_set_x( ui_PumpConfig_runtimePanel, 0 );
lv_obj_set_y( ui_PumpConfig_runtimePanel, -26 );
lv_obj_set_align( ui_PumpConfig_runtimePanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_runtimePanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PumpConfig_runtimePanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_PumpConfig_runtimePanel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_runtimePanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_PumpConfig_runtimePanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PumpConfig_runtimePanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PumpConfig_runtimePanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PumpConfig_runtimePanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PumpConfig_runtimePanel, lv_color_hex(0x6B8AF8), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_PumpConfig_runtimePanel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_PumpConfig_runtimeLabel = lv_label_create(ui_PumpConfig_runtimePanel);
lv_obj_set_width( ui_PumpConfig_runtimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_runtimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_runtimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_runtimeLabel,"Runtime");

ui_PumpConfig_runtimeValue = lv_label_create(ui_PumpConfig_runtimePanel);
lv_obj_set_width( ui_PumpConfig_runtimeValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_runtimeValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_runtimeValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_runtimeValue,"00:00");

ui_PumpConfig_minLightThresholdPanel = lv_obj_create(ui_PumpConfig_content);
lv_obj_set_height( ui_PumpConfig_minLightThresholdPanel, 40);
lv_obj_set_width( ui_PumpConfig_minLightThresholdPanel, lv_pct(100));
lv_obj_set_x( ui_PumpConfig_minLightThresholdPanel, -2 );
lv_obj_set_y( ui_PumpConfig_minLightThresholdPanel, -27 );
lv_obj_set_align( ui_PumpConfig_minLightThresholdPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_minLightThresholdPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PumpConfig_minLightThresholdPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_PumpConfig_minLightThresholdPanel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_minLightThresholdPanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_PumpConfig_minLightThresholdPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PumpConfig_minLightThresholdPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PumpConfig_minLightThresholdPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PumpConfig_minLightThresholdPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PumpConfig_minLightThresholdPanel, lv_color_hex(0x6B8AF8), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_PumpConfig_minLightThresholdPanel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_PumpConfig_minLightThresholdLabel = lv_label_create(ui_PumpConfig_minLightThresholdPanel);
lv_obj_set_width( ui_PumpConfig_minLightThresholdLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_minLightThresholdLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_minLightThresholdLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_minLightThresholdLabel,"Min. Light");

ui_PumpConfig_minLightThresholdValue = lv_label_create(ui_PumpConfig_minLightThresholdPanel);
lv_obj_set_width( ui_PumpConfig_minLightThresholdValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_minLightThresholdValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_minLightThresholdValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_minLightThresholdValue,"100%");

ui_PumpConfig_maxSoilThresholdPanel = lv_obj_create(ui_PumpConfig_content);
lv_obj_set_height( ui_PumpConfig_maxSoilThresholdPanel, 40);
lv_obj_set_width( ui_PumpConfig_maxSoilThresholdPanel, lv_pct(100));
lv_obj_set_align( ui_PumpConfig_maxSoilThresholdPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_maxSoilThresholdPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PumpConfig_maxSoilThresholdPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_PumpConfig_maxSoilThresholdPanel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_maxSoilThresholdPanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_PumpConfig_maxSoilThresholdPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PumpConfig_maxSoilThresholdPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PumpConfig_maxSoilThresholdPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PumpConfig_maxSoilThresholdPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PumpConfig_maxSoilThresholdPanel, lv_color_hex(0x6B8AF8), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_PumpConfig_maxSoilThresholdPanel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_PumpConfig_maxSoilThresholdLabel = lv_label_create(ui_PumpConfig_maxSoilThresholdPanel);
lv_obj_set_width( ui_PumpConfig_maxSoilThresholdLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_maxSoilThresholdLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_maxSoilThresholdLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_maxSoilThresholdLabel,"Max. Soil");

ui_PumpConfig_maxSoilThresholdValue = lv_label_create(ui_PumpConfig_maxSoilThresholdPanel);
lv_obj_set_width( ui_PumpConfig_maxSoilThresholdValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_maxSoilThresholdValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_maxSoilThresholdValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_maxSoilThresholdValue,"100%");

ui_PumpConfig_minTempThresholdPanel = lv_obj_create(ui_PumpConfig_content);
lv_obj_set_height( ui_PumpConfig_minTempThresholdPanel, 40);
lv_obj_set_width( ui_PumpConfig_minTempThresholdPanel, lv_pct(100));
lv_obj_set_align( ui_PumpConfig_minTempThresholdPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_minTempThresholdPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PumpConfig_minTempThresholdPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_PumpConfig_minTempThresholdPanel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_minTempThresholdPanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_PumpConfig_minTempThresholdPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PumpConfig_minTempThresholdPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PumpConfig_minTempThresholdPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PumpConfig_minTempThresholdPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PumpConfig_minTempThresholdPanel, lv_color_hex(0x6B8AF8), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_PumpConfig_minTempThresholdPanel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_PumpConfig_minTempThresholdLabel = lv_label_create(ui_PumpConfig_minTempThresholdPanel);
lv_obj_set_width( ui_PumpConfig_minTempThresholdLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_minTempThresholdLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_minTempThresholdLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_minTempThresholdLabel,"Min. Temp.");

ui_PumpConfig_minTempThresholdValue = lv_label_create(ui_PumpConfig_minTempThresholdPanel);
lv_obj_set_width( ui_PumpConfig_minTempThresholdValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_minTempThresholdValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_minTempThresholdValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_minTempThresholdValue,"10C");

ui_PumpConfig_maxHumidityThresholdPanel = lv_obj_create(ui_PumpConfig_content);
lv_obj_set_height( ui_PumpConfig_maxHumidityThresholdPanel, 40);
lv_obj_set_width( ui_PumpConfig_maxHumidityThresholdPanel, lv_pct(100));
lv_obj_set_align( ui_PumpConfig_maxHumidityThresholdPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_maxHumidityThresholdPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PumpConfig_maxHumidityThresholdPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_PumpConfig_maxHumidityThresholdPanel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_maxHumidityThresholdPanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_PumpConfig_maxHumidityThresholdPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PumpConfig_maxHumidityThresholdPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PumpConfig_maxHumidityThresholdPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PumpConfig_maxHumidityThresholdPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PumpConfig_maxHumidityThresholdPanel, lv_color_hex(0x6B8AF8), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_PumpConfig_maxHumidityThresholdPanel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_PumpConfig_maxHumidityThresholdLabel = lv_label_create(ui_PumpConfig_maxHumidityThresholdPanel);
lv_obj_set_width( ui_PumpConfig_maxHumidityThresholdLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_maxHumidityThresholdLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_maxHumidityThresholdLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_maxHumidityThresholdLabel,"Max. Humidity");

ui_PumpConfig_maxHumidityThresholdValue = lv_label_create(ui_PumpConfig_maxHumidityThresholdPanel);
lv_obj_set_width( ui_PumpConfig_maxHumidityThresholdValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_maxHumidityThresholdValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_maxHumidityThresholdValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_maxHumidityThresholdValue,"100%");

ui_PumpConfig_soilSensorDryPanel = lv_obj_create(ui_PumpConfig_content);
lv_obj_set_height( ui_PumpConfig_soilSensorDryPanel, 40);
lv_obj_set_width( ui_PumpConfig_soilSensorDryPanel, lv_pct(100));
lv_obj_set_align( ui_PumpConfig_soilSensorDryPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_soilSensorDryPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PumpConfig_soilSensorDryPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_PumpConfig_soilSensorDryPanel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_soilSensorDryPanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_PumpConfig_soilSensorDryPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PumpConfig_soilSensorDryPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PumpConfig_soilSensorDryPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PumpConfig_soilSensorDryPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PumpConfig_soilSensorDryPanel, lv_color_hex(0x6B8AF8), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_PumpConfig_soilSensorDryPanel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_PumpConfig_soilSensorDryLabel = lv_label_create(ui_PumpConfig_soilSensorDryPanel);
lv_obj_set_width( ui_PumpConfig_soilSensorDryLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_soilSensorDryLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_soilSensorDryLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_soilSensorDryLabel,"Soil Sensor Dry");

ui_PumpConfig_soilSensorDryValue = lv_label_create(ui_PumpConfig_soilSensorDryPanel);
lv_obj_set_width( ui_PumpConfig_soilSensorDryValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_soilSensorDryValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_soilSensorDryValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_soilSensorDryValue,"99999");

ui_PumpConfig_soilSensorWetPanel = lv_obj_create(ui_PumpConfig_content);
lv_obj_set_height( ui_PumpConfig_soilSensorWetPanel, 40);
lv_obj_set_width( ui_PumpConfig_soilSensorWetPanel, lv_pct(100));
lv_obj_set_align( ui_PumpConfig_soilSensorWetPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_soilSensorWetPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PumpConfig_soilSensorWetPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_PumpConfig_soilSensorWetPanel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_soilSensorWetPanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_PumpConfig_soilSensorWetPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PumpConfig_soilSensorWetPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PumpConfig_soilSensorWetPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PumpConfig_soilSensorWetPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PumpConfig_soilSensorWetPanel, lv_color_hex(0x6B8AF8), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_PumpConfig_soilSensorWetPanel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_PumpConfig_soilSensorWetLabel = lv_label_create(ui_PumpConfig_soilSensorWetPanel);
lv_obj_set_width( ui_PumpConfig_soilSensorWetLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_soilSensorWetLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_soilSensorWetLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_soilSensorWetLabel,"Soil Sensor Wet");

ui_PumpConfig_soilSensorWetValue = lv_label_create(ui_PumpConfig_soilSensorWetPanel);
lv_obj_set_width( ui_PumpConfig_soilSensorWetValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_soilSensorWetValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_soilSensorWetValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_soilSensorWetValue,"99999");

ui_PumpConfig_btn = lv_obj_create(ui_PumpConfig);
lv_obj_remove_style_all(ui_PumpConfig_btn);
lv_obj_set_width( ui_PumpConfig_btn, lv_pct(100));
lv_obj_set_height( ui_PumpConfig_btn, lv_pct(15));
lv_obj_set_x( ui_PumpConfig_btn, -1 );
lv_obj_set_y( ui_PumpConfig_btn, 0 );
lv_obj_set_align( ui_PumpConfig_btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PumpConfig_btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PumpConfig_btn, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_PumpConfig_btn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PumpConfig_btn1 = lv_button_create(ui_PumpConfig_btn);
lv_obj_set_width( ui_PumpConfig_btn1, lv_pct(31));
lv_obj_set_height( ui_PumpConfig_btn1, lv_pct(80));
lv_obj_set_x( ui_PumpConfig_btn1, 1 );
lv_obj_set_y( ui_PumpConfig_btn1, 2 );
lv_obj_set_align( ui_PumpConfig_btn1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PumpConfig_btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_btn1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PumpConfig_btn1Label = lv_label_create(ui_PumpConfig_btn1);
lv_obj_set_width( ui_PumpConfig_btn1Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_btn1Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_btn1Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_btn1Label,"Up/Back");

ui_PumpConfig_btn2 = lv_button_create(ui_PumpConfig_btn);
lv_obj_set_width( ui_PumpConfig_btn2, lv_pct(31));
lv_obj_set_height( ui_PumpConfig_btn2, lv_pct(80));
lv_obj_set_x( ui_PumpConfig_btn2, 1 );
lv_obj_set_y( ui_PumpConfig_btn2, 0 );
lv_obj_set_align( ui_PumpConfig_btn2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PumpConfig_btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_btn2, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PumpConfig_btn2Label = lv_label_create(ui_PumpConfig_btn2);
lv_obj_set_width( ui_PumpConfig_btn2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_btn2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_btn2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_btn2Label,"Down");

ui_PumpConfig_btn3 = lv_button_create(ui_PumpConfig_btn);
lv_obj_set_width( ui_PumpConfig_btn3, lv_pct(31));
lv_obj_set_height( ui_PumpConfig_btn3, lv_pct(80));
lv_obj_set_align( ui_PumpConfig_btn3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PumpConfig_btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_PumpConfig_btn3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PumpConfig_btn3Label = lv_label_create(ui_PumpConfig_btn3);
lv_obj_set_width( ui_PumpConfig_btn3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PumpConfig_btn3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PumpConfig_btn3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_PumpConfig_btn3Label,"Enter");

lv_obj_add_event_cb(ui_PumpConfig_btn1, ui_event_PumpConfig_btn1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PumpConfig_btn2, ui_event_PumpConfig_btn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PumpConfig_btn3, ui_event_PumpConfig_btn3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PumpConfig, ui_event_PumpConfig, LV_EVENT_ALL, NULL);

}
