// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: watering_system

#include "ui.h"

void ui_Settings_screen_init(void)
{
ui_Settings = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Settings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Settings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Settings_options = lv_roller_create(ui_Settings);
lv_roller_set_options( ui_Settings_options, "Pump 1\nPump 2\nPump 3\nWiFi\nExit", LV_ROLLER_MODE_INFINITE );
lv_obj_set_width( ui_Settings_options, lv_pct(100));
lv_obj_set_height( ui_Settings_options, lv_pct(80));
lv_obj_set_align( ui_Settings_options, LV_ALIGN_CENTER );

ui_Settings_btns = lv_obj_create(ui_Settings);
lv_obj_remove_style_all(ui_Settings_btns);
lv_obj_set_width( ui_Settings_btns, lv_pct(100));
lv_obj_set_height( ui_Settings_btns, lv_pct(15));
lv_obj_set_x( ui_Settings_btns, -1 );
lv_obj_set_y( ui_Settings_btns, 0 );
lv_obj_set_align( ui_Settings_btns, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Settings_btns,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Settings_btns, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Settings_btns, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_btn1 = lv_button_create(ui_Settings_btns);
lv_obj_set_width( ui_Settings_btn1, lv_pct(31));
lv_obj_set_height( ui_Settings_btn1, lv_pct(80));
lv_obj_set_x( ui_Settings_btn1, 1 );
lv_obj_set_y( ui_Settings_btn1, 2 );
lv_obj_set_align( ui_Settings_btn1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Settings_btn1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_btn1Label = lv_label_create(ui_Settings_btn1);
lv_obj_set_width( ui_Settings_btn1Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_btn1Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Settings_btn1Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Settings_btn1Label,"Up");

ui_Settings_btn2 = lv_button_create(ui_Settings_btns);
lv_obj_set_width( ui_Settings_btn2, lv_pct(31));
lv_obj_set_height( ui_Settings_btn2, lv_pct(80));
lv_obj_set_x( ui_Settings_btn2, 1 );
lv_obj_set_y( ui_Settings_btn2, 0 );
lv_obj_set_align( ui_Settings_btn2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Settings_btn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_btn2Label = lv_label_create(ui_Settings_btn2);
lv_obj_set_width( ui_Settings_btn2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_btn2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Settings_btn2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Settings_btn2Label,"Down");

ui_Settings_btn3 = lv_button_create(ui_Settings_btns);
lv_obj_set_width( ui_Settings_btn3, lv_pct(31));
lv_obj_set_height( ui_Settings_btn3, lv_pct(80));
lv_obj_set_align( ui_Settings_btn3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Settings_btn3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_btn3Label = lv_label_create(ui_Settings_btn3);
lv_obj_set_width( ui_Settings_btn3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_btn3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Settings_btn3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Settings_btn3Label,"Enter");

lv_obj_add_event_cb(ui_Settings_btn1, ui_event_Settings_btn1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_btn2, ui_event_Settings_btn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_btn3, ui_event_Settings_btn3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}
