// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: watering_system

#ifndef _WATERING_SYSTEM_UI_H
#define _WATERING_SYSTEM_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main( lv_event_t * e);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_Main_mainContainer;
extern lv_obj_t *ui_Main_infoPanel;
extern lv_obj_t *ui_Main_dateTimeConnContainer;
extern lv_obj_t *ui_Main_datetime;
extern lv_obj_t *ui_Main_connImg;
extern lv_obj_t *ui_Main_infoContainer;
extern lv_obj_t *ui_Main_tempImg;
extern lv_obj_t *ui_Main_tempLabel;
extern lv_obj_t *ui_Main_humidityImg;
extern lv_obj_t *ui_Main_humidityLabel;
extern lv_obj_t *ui_Main_contentContainer;
extern lv_obj_t *ui_Main_Pump1Container;
extern lv_obj_t *ui_Main_Pump2Container;
extern lv_obj_t *ui_Main_Pump3Container;
extern lv_obj_t *ui_Main_btnContainer;
void ui_event_Main_mainBtn1( lv_event_t * e);
extern lv_obj_t *ui_Main_mainBtn1;
extern lv_obj_t *ui_Main_mainBtn1Label;
void ui_event_Main_mainBtn2( lv_event_t * e);
extern lv_obj_t *ui_Main_mainBtn2;
extern lv_obj_t *ui_Main_mainBtn2Label;
void ui_event_Main_mainBtn3( lv_event_t * e);
extern lv_obj_t *ui_Main_mainBtn3;
extern lv_obj_t *ui_Main_mainBtn3Label;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings( lv_event_t * e);
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_Settings_options;
extern lv_obj_t *ui_Settings_btns;
void ui_event_Settings_btn1( lv_event_t * e);
extern lv_obj_t *ui_Settings_btn1;
extern lv_obj_t *ui_Settings_btn1Label;
void ui_event_Settings_btn2( lv_event_t * e);
extern lv_obj_t *ui_Settings_btn2;
extern lv_obj_t *ui_Settings_btn2Label;
void ui_event_Settings_btn3( lv_event_t * e);
extern lv_obj_t *ui_Settings_btn3;
extern lv_obj_t *ui_Settings_btn3Label;
// CUSTOM VARIABLES

// SCREEN: ui_PumpConfig
void ui_PumpConfig_screen_init(void);
void ui_event_PumpConfig( lv_event_t * e);
extern lv_obj_t *ui_PumpConfig;
extern lv_obj_t *ui_PumpConfig_titlePanel;
extern lv_obj_t *ui_PumpConfig_titleLabel;
extern lv_obj_t *ui_PumpConfig_content;
extern lv_obj_t *ui_PumpConfig_enabledPanel;
extern lv_obj_t *ui_PumpConfig_enabledLabel;
extern lv_obj_t *ui_PumpConfig_enabledSwitch;
extern lv_obj_t *ui_PumpConfig_frequencyPanel;
extern lv_obj_t *ui_PumpConfig_frequencyLabel;
extern lv_obj_t *ui_PumpConfig_frequencyValue;
extern lv_obj_t *ui_PumpConfig_runtimePanel;
extern lv_obj_t *ui_PumpConfig_runtimeLabel;
extern lv_obj_t *ui_PumpConfig_runtimeValue;
extern lv_obj_t *ui_PumpConfig_minLightThresholdPanel;
extern lv_obj_t *ui_PumpConfig_minLightThresholdLabel;
extern lv_obj_t *ui_PumpConfig_minLightThresholdValue;
extern lv_obj_t *ui_PumpConfig_maxSoilThresholdPanel;
extern lv_obj_t *ui_PumpConfig_maxSoilThresholdLabel;
extern lv_obj_t *ui_PumpConfig_maxSoilThresholdValue;
extern lv_obj_t *ui_PumpConfig_minTempThresholdPanel;
extern lv_obj_t *ui_PumpConfig_minTempThresholdLabel;
extern lv_obj_t *ui_PumpConfig_minTempThresholdValue;
extern lv_obj_t *ui_PumpConfig_maxHumidityThresholdPanel;
extern lv_obj_t *ui_PumpConfig_maxHumidityThresholdLabel;
extern lv_obj_t *ui_PumpConfig_maxHumidityThresholdValue;
extern lv_obj_t *ui_PumpConfig_soilSensorDryPanel;
extern lv_obj_t *ui_PumpConfig_soilSensorDryLabel;
extern lv_obj_t *ui_PumpConfig_soilSensorDryValue;
extern lv_obj_t *ui_PumpConfig_soilSensorWetPanel;
extern lv_obj_t *ui_PumpConfig_soilSensorWetLabel;
extern lv_obj_t *ui_PumpConfig_soilSensorWetValue;
extern lv_obj_t *ui_PumpConfig_btn;
void ui_event_PumpConfig_btn1( lv_event_t * e);
extern lv_obj_t *ui_PumpConfig_btn1;
extern lv_obj_t *ui_PumpConfig_btn1Label;
void ui_event_PumpConfig_btn2( lv_event_t * e);
extern lv_obj_t *ui_PumpConfig_btn2;
extern lv_obj_t *ui_PumpConfig_btn2Label;
void ui_event_PumpConfig_btn3( lv_event_t * e);
extern lv_obj_t *ui_PumpConfig_btn3;
extern lv_obj_t *ui_PumpConfig_btn3Label;
// CUSTOM VARIABLES

// SCREEN: ui_WiFiSettings
void ui_WiFiSettings_screen_init(void);
void ui_event_WiFiSettings( lv_event_t * e);
extern lv_obj_t *ui_WiFiSettings;
extern lv_obj_t *ui_WiFiSettings_infoContainer;
extern lv_obj_t *ui_WiFiSettings_ssidLabel;
extern lv_obj_t *ui_WiFiSettings_ipLabel;
extern lv_obj_t *ui_WiFiSettings_content;
extern lv_obj_t *ui_WiFiSettings_btnContainer;
void ui_event_WiFiSettings_btn1( lv_event_t * e);
extern lv_obj_t *ui_WiFiSettings_btn1;
extern lv_obj_t *ui_WiFiSettings_btn1Label;
void ui_event_WiFiSettings_btn2( lv_event_t * e);
extern lv_obj_t *ui_WiFiSettings_btn2;
extern lv_obj_t *ui_WiFiSettings_btn2Label;
void ui_event_WiFiSettings_btn3( lv_event_t * e);
extern lv_obj_t *ui_WiFiSettings_btn3;
extern lv_obj_t *ui_WiFiSettings_btn3Label;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_no_wifi_png);   // assets/no_wifi.png
LV_IMG_DECLARE( ui_img_temperature_png);   // assets/temperature.png
LV_IMG_DECLARE( ui_img_humidity_png);   // assets/humidity.png
LV_IMG_DECLARE( ui_img_plant_bad_png);   // assets/plant_bad.png
LV_IMG_DECLARE( ui_img_plant_good_png);   // assets/plant_good.png
LV_IMG_DECLARE( ui_img_sun_png);   // assets/sun.png
LV_IMG_DECLARE( ui_img_moon_png);   // assets/moon.png
LV_IMG_DECLARE( ui_img_day_and_night_png);   // assets/day_and_night.png
LV_IMG_DECLARE( ui_img_sprinkler_png);   // assets/sprinkler.png
LV_IMG_DECLARE( ui_img_sprinkler_off_png);   // assets/sprinkler_off.png
LV_IMG_DECLARE( ui_img_wifi_png);   // assets/wifi.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
