// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: watering_system

#include "ui.h"


// COMPONENT PumpContainer

lv_obj_t *ui_PumpContainer_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_PumpContainer;
cui_PumpContainer = lv_obj_create(comp_parent);
lv_obj_set_height( cui_PumpContainer, 42);
lv_obj_set_width( cui_PumpContainer, lv_pct(98));
lv_obj_set_x( cui_PumpContainer, -1 );
lv_obj_set_y( cui_PumpContainer, 0 );
lv_obj_set_align( cui_PumpContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_PumpContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_PumpContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( cui_PumpContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(cui_PumpContainer, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_PumpContainer, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_PumpContainer, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_PumpContainer, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_PumpContainer, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(cui_PumpContainer, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_border_color(cui_PumpContainer, lv_color_hex(0x4974ED), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(cui_PumpContainer, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

lv_obj_t *cui_labelContainer;
cui_labelContainer = lv_obj_create(cui_PumpContainer);
lv_obj_remove_style_all(cui_labelContainer);
lv_obj_set_width( cui_labelContainer, 32);
lv_obj_set_height( cui_labelContainer, 32);
lv_obj_set_align( cui_labelContainer, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_labelContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_running;
cui_running = lv_spinner_create(cui_labelContainer);
//lv_spinner_set_anim_params(cui_running, 1000, 90);
lv_obj_set_width( cui_running, 32);
lv_obj_set_height( cui_running, 32);
lv_obj_set_align( cui_running, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_running, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_arc_width(cui_running, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(cui_running, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(cui_running, lv_color_hex(0x737373), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_arc_opa(cui_running, 255, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_t *cui_label;
cui_label = lv_label_create(cui_labelContainer);
lv_obj_set_width( cui_label, 32);
lv_obj_set_height( cui_label, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( cui_label, 0 );
lv_obj_set_y( cui_label, 1 );
lv_obj_set_align( cui_label, LV_ALIGN_CENTER );
lv_label_set_text(cui_label,"1");
lv_obj_set_style_text_align(cui_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_label, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(cui_label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_text_opa(cui_label, 255, LV_PART_MAIN| LV_STATE_DISABLED);

lv_obj_t *cui_soil;
cui_soil = lv_arc_create(cui_PumpContainer);
lv_obj_set_width( cui_soil, 32);
lv_obj_set_height( cui_soil, 32);
lv_obj_set_align( cui_soil, LV_ALIGN_CENTER );
lv_obj_add_state( cui_soil, LV_STATE_USER_1 );     /// States
lv_arc_set_value(cui_soil, 0);
lv_obj_set_style_arc_width(cui_soil, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor(cui_soil, lv_color_hex(0x6E6E6E), LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_bg_image_recolor_opa(cui_soil, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_bg_image_src( cui_soil, &ui_img_plant_bad_png, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_src( cui_soil, &ui_img_plant_good_png, LV_PART_MAIN | LV_STATE_USER_2 );

lv_obj_set_style_arc_width(cui_soil, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(cui_soil, lv_color_hex(0x737373), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_arc_opa(cui_soil, 255, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_pad_left(cui_soil, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_soil, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_soil, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_soil, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_soil, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(cui_soil, 0, LV_PART_KNOB| LV_STATE_DISABLED);

lv_obj_t *cui_light;
cui_light = lv_arc_create(cui_PumpContainer);
lv_obj_set_width( cui_light, 32);
lv_obj_set_height( cui_light, 32);
lv_obj_set_align( cui_light, LV_ALIGN_CENTER );
lv_obj_add_state( cui_light, LV_STATE_USER_1 );     /// States
lv_arc_set_value(cui_light, 0);
lv_obj_set_style_arc_width(cui_light, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor(cui_light, lv_color_hex(0x6E6E6E), LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_bg_image_recolor_opa(cui_light, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_bg_image_src( cui_light, &ui_img_sun_png, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_src( cui_light, &ui_img_moon_png, LV_PART_MAIN | LV_STATE_USER_2 );

lv_obj_set_style_arc_width(cui_light, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(cui_light, lv_color_hex(0x737373), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_arc_opa(cui_light, 255, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_pad_left(cui_light, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_light, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_light, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_light, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_light, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(cui_light, 0, LV_PART_KNOB| LV_STATE_DISABLED);

lv_obj_t *cui_progress;
cui_progress = lv_bar_create(cui_PumpContainer);
lv_bar_set_mode(cui_progress, LV_BAR_MODE_SYMMETRICAL);
lv_bar_set_value(cui_progress,25,LV_ANIM_OFF);
lv_bar_set_start_value(cui_progress, 0, LV_ANIM_OFF);
lv_obj_set_width( cui_progress, 70);
lv_obj_set_height( cui_progress, 10);
lv_obj_set_x( cui_progress, -19 );
lv_obj_set_y( cui_progress, -15 );
lv_obj_set_align( cui_progress, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(cui_progress, lv_color_hex(0xC3C3C3), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(cui_progress, 255, LV_PART_MAIN| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(cui_progress, lv_color_hex(0x565656), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(cui_progress, 255, LV_PART_INDICATOR| LV_STATE_DISABLED);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(cui_progress,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( cui_progress, lv_obj_get_style_pad_right(cui_progress,LV_PART_MAIN) + 1, LV_PART_MAIN );
lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PUMPCONTAINER_NUM);
children[UI_COMP_PUMPCONTAINER_PUMPCONTAINER] = cui_PumpContainer;
children[UI_COMP_PUMPCONTAINER_LABELCONTAINER] = cui_labelContainer;
children[UI_COMP_PUMPCONTAINER_LABELCONTAINER_RUNNING] = cui_running;
children[UI_COMP_PUMPCONTAINER_LABELCONTAINER_LABEL] = cui_label;
children[UI_COMP_PUMPCONTAINER_SOIL] = cui_soil;
children[UI_COMP_PUMPCONTAINER_LIGHT] = cui_light;
children[UI_COMP_PUMPCONTAINER_PROGRESS] = cui_progress;
lv_obj_add_event_cb(cui_PumpContainer, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_PumpContainer, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_PumpContainer_create_hook(cui_PumpContainer);
return cui_PumpContainer; 
}

