// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: watering_system

#include "ui.h"

void ui_comp_PumpContainer_create_hook( lv_obj_t * comp)
{
}
