// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: watering_system

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onMainScreenLoaded(lv_event_t * e);
void onMainScreenUnloaded(lv_event_t * e);
void onRunButtonClicked(lv_event_t * e);
void onPumpButtonClicked(lv_event_t * e);
void onSettingsScreenLoaded(lv_event_t * e);
void onSettingsUpButtonClicked(lv_event_t * e);
void onSettingsDownClicked(lv_event_t * e);
void onSettingsEnterClicked(lv_event_t * e);
void onPumpScreenLoaded(lv_event_t * e);
void onPumpConfigBtn1Clicked(lv_event_t * e);
void onPumpConfigBtn1LongPressed(lv_event_t * e);
void onPumpConfigBtn2Clicked(lv_event_t * e);
void onPumpConfigBtn2LongPressed(lv_event_t * e);
void onPumpConfigBtn3Clicked(lv_event_t * e);
void onWifiSettingsLoaded(lv_event_t * e);
void onWifiSettingsUnloaded(lv_event_t * e);
void onWifiScreenBtn1Clicked(lv_event_t * e);
void onWifiScreenBtn2Clicked(lv_event_t * e);
void onWifiScreenBtn3Clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
