// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: watering_system

#include "ui.h"

void ui_Main_screen_init(void)
{
ui_Main = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Main_mainContainer = lv_obj_create(ui_Main);
lv_obj_remove_style_all(ui_Main_mainContainer);
lv_obj_set_width( ui_Main_mainContainer, lv_pct(100));
lv_obj_set_height( ui_Main_mainContainer, lv_pct(100));
lv_obj_set_align( ui_Main_mainContainer, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_Main_mainContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Main_mainContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
lv_obj_remove_flag( ui_Main_mainContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Main_infoPanel = lv_obj_create(ui_Main_mainContainer);
lv_obj_set_width( ui_Main_infoPanel, lv_pct(98));
lv_obj_set_height( ui_Main_infoPanel, lv_pct(30));
lv_obj_set_x( ui_Main_infoPanel, 1 );
lv_obj_set_y( ui_Main_infoPanel, 0 );
lv_obj_set_align( ui_Main_infoPanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Main_infoPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Main_infoPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Main_infoPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Main_infoPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Main_infoPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Main_infoPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Main_infoPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Main_dateTimeConnContainer = lv_obj_create(ui_Main_infoPanel);
lv_obj_remove_style_all(ui_Main_dateTimeConnContainer);
lv_obj_set_width( ui_Main_dateTimeConnContainer, lv_pct(100));
lv_obj_set_height( ui_Main_dateTimeConnContainer, lv_pct(50));
lv_obj_set_align( ui_Main_dateTimeConnContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Main_dateTimeConnContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Main_dateTimeConnContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Main_dateTimeConnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Main_datetime = lv_label_create(ui_Main_dateTimeConnContainer);
lv_obj_set_width( ui_Main_datetime, lv_pct(90));
lv_obj_set_height( ui_Main_datetime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Main_datetime, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Main_datetime,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_Main_datetime,"Mon. 28 Oct 2024 21:47:44");
lv_obj_set_style_text_align(ui_Main_datetime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Main_datetime, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Main_connImg = lv_image_create(ui_Main_dateTimeConnContainer);
lv_image_set_src(ui_Main_connImg, &ui_img_no_wifi_png);
lv_obj_set_width( ui_Main_connImg, 24);
lv_obj_set_height( ui_Main_connImg, 24);
lv_obj_set_align( ui_Main_connImg, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Main_connImg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Main_connImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Main_connImg,254);
lv_image_set_inner_align( ui_Main_connImg, LV_IMAGE_ALIGN_STRETCH );

ui_Main_infoContainer = lv_obj_create(ui_Main_infoPanel);
lv_obj_remove_style_all(ui_Main_infoContainer);
lv_obj_set_width( ui_Main_infoContainer, lv_pct(100));
lv_obj_set_height( ui_Main_infoContainer, lv_pct(50));
lv_obj_set_x( ui_Main_infoContainer, 1 );
lv_obj_set_y( ui_Main_infoContainer, 0 );
lv_obj_set_align( ui_Main_infoContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Main_infoContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Main_infoContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Main_infoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Main_tempImg = lv_image_create(ui_Main_infoContainer);
lv_image_set_src(ui_Main_tempImg, &ui_img_temperature_png);
lv_obj_set_width( ui_Main_tempImg, 24);
lv_obj_set_height( ui_Main_tempImg, 24);
lv_obj_set_align( ui_Main_tempImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Main_tempImg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Main_tempImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_inner_align( ui_Main_tempImg, LV_IMAGE_ALIGN_STRETCH );

ui_Main_tempLabel = lv_label_create(ui_Main_infoContainer);
lv_obj_set_width( ui_Main_tempLabel, 60);
lv_obj_set_height( ui_Main_tempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Main_tempLabel, 0 );
lv_obj_set_y( ui_Main_tempLabel, 2 );
lv_obj_set_align( ui_Main_tempLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Main_tempLabel,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_Main_tempLabel,"-100.2°C");

ui_Main_humidityImg = lv_image_create(ui_Main_infoContainer);
lv_image_set_src(ui_Main_humidityImg, &ui_img_humidity_png);
lv_obj_set_width( ui_Main_humidityImg, 24);
lv_obj_set_height( ui_Main_humidityImg, 24);
lv_obj_set_x( ui_Main_humidityImg, 34 );
lv_obj_set_y( ui_Main_humidityImg, -69 );
lv_obj_set_align( ui_Main_humidityImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Main_humidityImg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Main_humidityImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_inner_align( ui_Main_humidityImg, LV_IMAGE_ALIGN_STRETCH );

ui_Main_humidityLabel = lv_label_create(ui_Main_infoContainer);
lv_obj_set_width( ui_Main_humidityLabel, 60);
lv_obj_set_height( ui_Main_humidityLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Main_humidityLabel, 0 );
lv_obj_set_y( ui_Main_humidityLabel, -2 );
lv_obj_set_align( ui_Main_humidityLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Main_humidityLabel,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_Main_humidityLabel,"100.0");

ui_Main_contentContainer = lv_obj_create(ui_Main_mainContainer);
lv_obj_remove_style_all(ui_Main_contentContainer);
lv_obj_set_width( ui_Main_contentContainer, lv_pct(100));
lv_obj_set_height( ui_Main_contentContainer, lv_pct(55));
lv_obj_set_x( ui_Main_contentContainer, 0 );
lv_obj_set_y( ui_Main_contentContainer, -2 );
lv_obj_set_align( ui_Main_contentContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Main_contentContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Main_contentContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Main_contentContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Main_Pump1Container = ui_PumpContainer_create(ui_Main_contentContainer);
lv_obj_set_x( ui_Main_Pump1Container, -1 );
lv_obj_set_y( ui_Main_Pump1Container, 0 );










//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
ui_Main_Pump2Container = ui_PumpContainer_create(ui_Main_contentContainer);
lv_obj_set_x( ui_Main_Pump2Container, 1 );
lv_obj_set_y( ui_Main_Pump2Container, 0 );










//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
ui_Main_Pump3Container = ui_PumpContainer_create(ui_Main_contentContainer);
lv_obj_set_x( ui_Main_Pump3Container, 0 );
lv_obj_set_y( ui_Main_Pump3Container, 0 );










//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
ui_Main_btnContainer = lv_obj_create(ui_Main_mainContainer);
lv_obj_remove_style_all(ui_Main_btnContainer);
lv_obj_set_width( ui_Main_btnContainer, lv_pct(100));
lv_obj_set_height( ui_Main_btnContainer, lv_pct(15));
lv_obj_set_align( ui_Main_btnContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Main_btnContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Main_btnContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Main_btnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Main_mainBtn1 = lv_button_create(ui_Main_btnContainer);
lv_obj_set_width( ui_Main_mainBtn1, lv_pct(31));
lv_obj_set_height( ui_Main_mainBtn1, lv_pct(80));
lv_obj_set_x( ui_Main_mainBtn1, 0 );
lv_obj_set_y( ui_Main_mainBtn1, 2 );
lv_obj_set_align( ui_Main_mainBtn1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Main_mainBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Main_mainBtn1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Main_mainBtn1Label = lv_label_create(ui_Main_mainBtn1);
lv_obj_set_width( ui_Main_mainBtn1Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Main_mainBtn1Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Main_mainBtn1Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Main_mainBtn1Label,"Settings");

ui_Main_mainBtn2 = lv_button_create(ui_Main_btnContainer);
lv_obj_set_width( ui_Main_mainBtn2, lv_pct(31));
lv_obj_set_height( ui_Main_mainBtn2, lv_pct(80));
lv_obj_set_x( ui_Main_mainBtn2, 1 );
lv_obj_set_y( ui_Main_mainBtn2, 0 );
lv_obj_set_align( ui_Main_mainBtn2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Main_mainBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Main_mainBtn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Main_mainBtn2Label = lv_label_create(ui_Main_mainBtn2);
lv_obj_set_width( ui_Main_mainBtn2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Main_mainBtn2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Main_mainBtn2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Main_mainBtn2Label,"Run");

ui_Main_mainBtn3 = lv_button_create(ui_Main_btnContainer);
lv_obj_set_width( ui_Main_mainBtn3, lv_pct(31));
lv_obj_set_height( ui_Main_mainBtn3, lv_pct(80));
lv_obj_set_align( ui_Main_mainBtn3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Main_mainBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Main_mainBtn3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Main_mainBtn3Label = lv_label_create(ui_Main_mainBtn3);
lv_obj_set_width( ui_Main_mainBtn3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Main_mainBtn3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Main_mainBtn3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Main_mainBtn3Label,"Pump");

lv_obj_add_event_cb(ui_Main_mainBtn1, ui_event_Main_mainBtn1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Main_mainBtn2, ui_event_Main_mainBtn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Main_mainBtn3, ui_event_Main_mainBtn3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Main, ui_event_Main, LV_EVENT_ALL, NULL);

}
