// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: watering_system

#include "ui.h"

void ui_WiFiSettings_screen_init(void)
{
ui_WiFiSettings = lv_obj_create(NULL);
lv_obj_remove_flag( ui_WiFiSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_WiFiSettings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_WiFiSettings, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_WiFiSettings_infoContainer = lv_obj_create(ui_WiFiSettings);
lv_obj_set_width( ui_WiFiSettings_infoContainer, lv_pct(100));
lv_obj_set_height( ui_WiFiSettings_infoContainer, lv_pct(30));
lv_obj_set_align( ui_WiFiSettings_infoContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_WiFiSettings_infoContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_WiFiSettings_infoContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_WiFiSettings_infoContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WiFiSettings_ssidLabel = lv_label_create(ui_WiFiSettings_infoContainer);
lv_obj_set_width( ui_WiFiSettings_ssidLabel, lv_pct(100));
lv_obj_set_height( ui_WiFiSettings_ssidLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WiFiSettings_ssidLabel, 36 );
lv_obj_set_y( ui_WiFiSettings_ssidLabel, -38 );
lv_obj_set_align( ui_WiFiSettings_ssidLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WiFiSettings_ssidLabel,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_WiFiSettings_ssidLabel,"Connected to CyMano");
lv_obj_set_style_text_align(ui_WiFiSettings_ssidLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WiFiSettings_ipLabel = lv_label_create(ui_WiFiSettings_infoContainer);
lv_obj_set_width( ui_WiFiSettings_ipLabel, lv_pct(100));
lv_obj_set_height( ui_WiFiSettings_ipLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WiFiSettings_ipLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WiFiSettings_ipLabel,"192.168.254.254");
lv_obj_set_style_text_align(ui_WiFiSettings_ipLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WiFiSettings_ipLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WiFiSettings_content = lv_obj_create(ui_WiFiSettings);
lv_obj_remove_style_all(ui_WiFiSettings_content);
lv_obj_set_width( ui_WiFiSettings_content, lv_pct(100));
lv_obj_set_height( ui_WiFiSettings_content, lv_pct(50));
lv_obj_set_align( ui_WiFiSettings_content, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_WiFiSettings_content,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_WiFiSettings_content, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_WiFiSettings_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WiFiSettings_btnContainer = lv_obj_create(ui_WiFiSettings);
lv_obj_remove_style_all(ui_WiFiSettings_btnContainer);
lv_obj_set_width( ui_WiFiSettings_btnContainer, lv_pct(100));
lv_obj_set_height( ui_WiFiSettings_btnContainer, lv_pct(15));
lv_obj_set_x( ui_WiFiSettings_btnContainer, -1 );
lv_obj_set_y( ui_WiFiSettings_btnContainer, 0 );
lv_obj_set_align( ui_WiFiSettings_btnContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_WiFiSettings_btnContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_WiFiSettings_btnContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_WiFiSettings_btnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WiFiSettings_btn1 = lv_button_create(ui_WiFiSettings_btnContainer);
lv_obj_set_width( ui_WiFiSettings_btn1, lv_pct(31));
lv_obj_set_height( ui_WiFiSettings_btn1, lv_pct(80));
lv_obj_set_x( ui_WiFiSettings_btn1, 1 );
lv_obj_set_y( ui_WiFiSettings_btn1, 2 );
lv_obj_set_align( ui_WiFiSettings_btn1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WiFiSettings_btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_WiFiSettings_btn1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WiFiSettings_btn1Label = lv_label_create(ui_WiFiSettings_btn1);
lv_obj_set_width( ui_WiFiSettings_btn1Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WiFiSettings_btn1Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WiFiSettings_btn1Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_WiFiSettings_btn1Label,"Back");

ui_WiFiSettings_btn2 = lv_button_create(ui_WiFiSettings_btnContainer);
lv_obj_set_width( ui_WiFiSettings_btn2, lv_pct(31));
lv_obj_set_height( ui_WiFiSettings_btn2, lv_pct(80));
lv_obj_set_x( ui_WiFiSettings_btn2, 1 );
lv_obj_set_y( ui_WiFiSettings_btn2, 0 );
lv_obj_set_align( ui_WiFiSettings_btn2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WiFiSettings_btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_WiFiSettings_btn2, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WiFiSettings_btn2Label = lv_label_create(ui_WiFiSettings_btn2);
lv_obj_set_width( ui_WiFiSettings_btn2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WiFiSettings_btn2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WiFiSettings_btn2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_WiFiSettings_btn2Label,"Disconn.");

ui_WiFiSettings_btn3 = lv_button_create(ui_WiFiSettings_btnContainer);
lv_obj_set_width( ui_WiFiSettings_btn3, lv_pct(31));
lv_obj_set_height( ui_WiFiSettings_btn3, lv_pct(80));
lv_obj_set_align( ui_WiFiSettings_btn3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WiFiSettings_btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_WiFiSettings_btn3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WiFiSettings_btn3Label = lv_label_create(ui_WiFiSettings_btn3);
lv_obj_set_width( ui_WiFiSettings_btn3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WiFiSettings_btn3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WiFiSettings_btn3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_WiFiSettings_btn3Label,"Reset");

lv_obj_add_event_cb(ui_WiFiSettings_btn1, ui_event_WiFiSettings_btn1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WiFiSettings_btn2, ui_event_WiFiSettings_btn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WiFiSettings_btn3, ui_event_WiFiSettings_btn3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WiFiSettings, ui_event_WiFiSettings, LV_EVENT_ALL, NULL);

}
