globals:
  - id: pump_1_last_run
    type: int
    restore_value: yes
    initial_value: '0'
  - id: pump_2_last_run
    type: int
    restore_value: yes
    initial_value: '0'
  - id: pump_3_last_run
    type: int
    restore_value: yes
    initial_value: '0'