sprinkler:
  - id: sprinkler_ctrlr
    main_switch: "Sprinklers"
    auto_advance_switch: "Auto Advance"
    valves:
      - valve_switch: "Pump 1"
        enable_switch: "Enable Pump 1"
        run_duration_number:
          id: pump_1_run_duration
          name: "Pump 1 Run Duration"
          min_value: 0
          max_value: 600
          initial_value: 60
          step: 1
        valve_switch_id: pump_1_sw
      - valve_switch: "Pump 2"
        enable_switch: "Enable Pump 2"
        run_duration_number:
          id: pump_2_run_duration
          name: "Pump 2 Run Duration"
          min_value: 0
          max_value: 600
          initial_value: 60
          step: 1
        valve_switch_id: pump_2_sw
      - valve_switch: "Pump 3"
        enable_switch: "Enable Pump 3"
        run_duration_number:
          id: pump_3_run_duration
          name: "Pump 3 Run Duration"
          min_value: 0
          max_value: 600
          initial_value: 60
          step: 1
        valve_switch_id: pump_3_sw
