esphome:
  name: wateringsystem
  friendly_name: Watering System
  min_version: 2025.4.1
  includes:
    - internal/functions.cpp
  project:
    name: "manoamaro.watering_system"
    version: "1.0.0"
preferences:
  flash_write_interval: 10min

substitutions:
  update_sensors_interval: 10s

packages:
  lvgl: !include internal/ui/lvgl.yaml
  pump0: !include
    file: internal/pump.yaml
    vars:
      id: 1
      pin: GPIO12
      soil_sensor_pin: GPIO39
  pump1: !include
    file: internal/pump.yaml
    vars:
      id: 2
      pin: GPIO4
      soil_sensor_pin: GPIO34
  pump2: !include
    file: internal/pump.yaml
    vars:
      id: 3
      pin: GPIO14
      soil_sensor_pin: GPIO35

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  reboot_timeout: 0s

wifi:
  power_save_mode: none
  output_power: 20dBm
  ap:
    ssid: "Watering System"

captive_portal:

#http_request:
#  verify_ssl: false

ota:
#  - platform: http_request
  - platform: esphome

mdns:

#update:
#  - platform: http_request
#    name: Firmware Update
#    source: http://example.com/manifest.json

time:
  - platform: homeassistant
    id: global_time

i2c:
  sda: 21
  scl: 22
  scan: True

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

sensor:
  - platform: bme280_i2c
    id: bme280_sensor
    address: 0x76
    update_interval: $update_sensors_interval
    temperature:
      id: bme280_temperature
      name: "Temperature"
      filters:
        - round: 2
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
      on_value:
        then:      
          - lvgl.label.update:
              id: lbl_temperature
              text:
                format: "%.1f°C"
                args: [x]
    pressure:
      id: bme280_pressure
      name: "Pressure"
      filters:
        - round: 2
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    humidity:
      id: bme280_humidity
      name: "Humidity"
      filters:
        - round: 2
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
      on_value:
        then:      
          - lvgl.label.update:
              id: lbl_humidity
              text:
                format: "%.1f%%"
                args: [x]
  - platform: adc
    id: light_sensor
    pin: GPIO36
    name: "Light Sensor"
    update_interval: $update_sensors_interval
    attenuation: 12db
    unit_of_measurement: "%"
    filters:
      - round: 2
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
      - calibrate_linear:
          method: exact
          datapoints:
            - 0.0 -> 0.0
            - 3.3 -> 100.0
      - clamp:
          min_value: 0
          max_value: 100
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 10s
    entity_category: "diagnostic"
