---
id: main_page
styles: page
scrollbar_mode: "OFF"
layout:
  type: FLEX
  flex_flow: COLUMN
  flex_align_main: SPACE_AROUND
  flex_align_cross: CENTER
  flex_align_track: CENTER
widgets:
  - !include
    file: pump_info_component.yaml
    vars:
      id: 0
  - !include
    file: pump_info_component.yaml
    vars:
      id: 1
  - !include
    file: pump_info_component.yaml
    vars:
      id: 2
