obj:
  id: obj_pump_${id}_info
  styles: [pump_info]
  group: main_group
  layout:
    type: FLEX
    flex_flow: ROW
    flex_align_main: SPACE_BETWEEN
    flex_align_cross: CENTER
    flex_align_track: CENTER
  click_focusable: false
  clickable: true
  scrollable: false
  focused:
    border_color: 0x4024e2
    border_width: 2
  on_click:
    then:
      - script.execute: force_run_pump_${id}
  on_long_press:
    then:
      - lvgl.page.show:
          id: pump_${id}_page
  widgets:
    - label:
        id: lbl_pump_${id}
        text_font: montserrat_24_mdi
        text: "\U000F1060 ${id}"
        text_color: 0x24c6e2
        width: 60
        pad_left: 5
        disabled:
          text_color: 0xe24024
    - image:
        id: img_pump_${id}_light
        pad_left: 5
        src: sun
        disabled:
          image_recolor: 0x000000
    - image:
        id: img_pump_${id}_soil
        pad_left: 5
        src: plant_dry
        disabled:
          image_recolor: 0x000000
    - label:
        id: lbl_pump_${id}_next
        pad_left: 5
        text: "00:00:00"
        width: 80
    - spinner:
        id: spinner_pump_${id}
        spin_time: 2s
        arc_length: 60deg
        arc_width: 4
        width: 24
        height: 24
        indicator:
          arc_width: 4
